// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVZ8NkF62kk8obM7xyrITfAb4pgKtLLI',
    appId: '1:685873349714:web:ae9cc25ec4f7aff2958b8b',
    messagingSenderId: '685873349714',
    projectId: 'therapp-1ee4c',
    authDomain: 'therapp-1ee4c.firebaseapp.com',
    storageBucket: 'therapp-1ee4c.firebasestorage.app',
    measurementId: 'G-04BE14DMDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmQO2MG5hmDChhP-P3gMma0j0Zws3zwks',
    appId: '1:685873349714:android:47a449269cfbfb90958b8b',
    messagingSenderId: '685873349714',
    projectId: 'therapp-1ee4c',
    storageBucket: 'therapp-1ee4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQE3lqQNSnoVF9AN5dCPBURB0WlPbqA4',
    appId: '1:685873349714:ios:b63e0e8cc1990655958b8b',
    messagingSenderId: '685873349714',
    projectId: 'therapp-1ee4c',
    storageBucket: 'therapp-1ee4c.firebasestorage.app',
    iosBundleId: 'com.example.theraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQE3lqQNSnoVF9AN5dCPBURB0WlPbqA4',
    appId: '1:685873349714:ios:b63e0e8cc1990655958b8b',
    messagingSenderId: '685873349714',
    projectId: 'therapp-1ee4c',
    storageBucket: 'therapp-1ee4c.firebasestorage.app',
    iosBundleId: 'com.example.theraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoVZ8NkF62kk8obM7xyrITfAb4pgKtLLI',
    appId: '1:685873349714:web:3a0d0229701a835d958b8b',
    messagingSenderId: '685873349714',
    projectId: 'therapp-1ee4c',
    authDomain: 'therapp-1ee4c.firebaseapp.com',
    storageBucket: 'therapp-1ee4c.firebasestorage.app',
    measurementId: 'G-6FGH55P6WW',
  );

}